### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by prnvtripathi** [gdsc-abesit/GDSC-ABESIT#13]
Create Contributing.md file for contribution guidelines

**Comment by uditi1002** [comment]
can i be assigned to this issue?

**Comment by prnvtripathi** [comment]
Surely. Go for it. @uditi1002

**Comment by uditi1002** [comment]
It shows this error while running the code. 

[Error: ENOENT: no such file or directory, open 'D:\open source\GDSC-ABESIT\.next\BUILD_ID'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\open source\\GDSC-ABESIT\\.next\\BUILD_ID'
}

**Comment by Arcturus22** [comment]
@prnvtripathi @JoshLamptey
What is to be added in the Contributing markdown

**Comment by prnvtripathi** [comment]
solved in #16
