### ISSUE TITLE
GDSC name not visible due to transparent background

### ISSUE THREAD

**Issue by Suhaani07** [gdsc-abesit/GDSC-ABESIT#68]
![Screenshot_2023-10-14-16-07-32-09](https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/9c7ee1a4-078e-47e0-b907-38cfca6335ff)

Will change the colour of the gdsc test to White instead of black. Kindly assign me this issue under hacktoberfest

**Comment by prnvtripathi** [comment]
i can't see this bug on my device, can you please elaborate more

**Comment by Suhaani07** [comment]
Sure. Here is the before picture :
<img width="1080" alt="image" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/f1ef2310-ad47-4429-97e3-9b0ae9147923">
As you can see, no colour is assigned to the GDSC Name due to while it is looking black and hence not visible.
I'll assign wheat color to it so that it looks like this : 
<img width="1080" alt="image" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/714c6466-c4e8-4e10-bc69-55fde56e72da">
Kindly assign me this issue under Hacktoberfest 2023

**Comment by Ishaan2053** [comment]
Sure! Go ahead, start working :)
However, please use `text-gray-100` instead of wheat color
