### ISSUE TITLE
Hovering Effects in Navbar Section 

### ISSUE THREAD

**Issue by DeepRahangdale** [gdsc-abesit/GDSC-ABESIT#72]
Adding the hovering effect over Home, Events, Projects, team and Contributors.
For the better user experience.
Add under Hacktoberfest

**Comment by Ishaan2053** [comment]
Seems like a good idea, would love to see how that turns out!
Do you want to be assigned this issue?

**Comment by SathvikKandadi** [comment]
Hey Can you assign me this ?

**Comment by Ishaan2053** [comment]
Well sure can! 
Just make sure to keep the effect subtle though. For example: a component hover effect (say, a button) should have properties such as `hover:scale-105` or `hover:scale-95`. 

That'll ensure interactivity while being minimal.

**Comment by DeepRahangdale** [comment]
assign me!!

**Comment by Ishaan2053** [comment]
Sorry Deep Satvik's already assigned to this issue.
However, you guys can maybe team up and co-author commits on this issue's PR. That way both of you will earn the **_pair extraordinaire_** badge

Wouldn't that be a great addition to your profiles :)

**Comment by Ishaan2053** [comment]
I'm assigning this issue to you too. Looking forward to the PR 🙂
