### ISSUE TITLE
Team page UI fix

### ISSUE THREAD

**Issue by Suhaani07** [gdsc-abesit/GDSC-ABESIT#73]
On mobile view, the team members page is not responsive.
<img width="365" alt="image" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/e628a7a3-43ad-4216-aaa0-b4e296b761de">
Kindly assign me this issue under hacktoberfest 2023. I'll adjust the icons such that on smaller screens, the cards will appear 1 in each row.

**Comment by Ishaan2053** [comment]
Sure, go ahead! I'll assign it to you.

**Comment by DebidYadav** [comment]
Hello, I have fixed this issue, opening PR, please check.

**Comment by Suhaani07** [comment]
@Ishaan2053 have opened up the PR since you have assigned it to me. Kindly check it  out #85
