### ISSUE TITLE
Feat: Add 'Load More' Button In Contributors section

### ISSUE THREAD

**Issue by Ayusht777** [gdsc-abesit/GDSC-ABESIT#75]
for UI perspective it doesn't looks good to show all this in list in mobile view adding load more button will be good  also the logo of twitter / X is inconsistent so fixing it will be good and if some person doesn't have image so we can add some generic image or use their LinkedIn or X account image  which will be store locally etc 

![image](https://github.com/gdsc-abesit/GDSC-ABESIT/assets/106388215/716e701b-1cb2-49c9-a868-e8ac400288f6)

**Comment by Ishaan2053** [comment]
Social icons for this page are **_generated_** using `react-social-icons`, keeping in mind flexibility for contributors to add whatever social link they want.
These inconsistencies occur due to people using X and Twitter freely for their socials (and since both links are valid, they don't raise any problems).

**Comment by Ishaan2053** [comment]
Having generic images for people without images though seems like a good idea. Also, for mobile view, along with a 'load more' button we can maybe even go for slightly shorter cards, which will, in turn improve the UI.

Would you want to be assigned this issue under HacktoberFest 2023?

**Comment by Ayusht777** [comment]
Yes, I will work on it I want to know that you are rendering these cards using local data or any database because I didn't know how use the database method

**Comment by Ishaan2053** [comment]
Oh these cards don't use a database. It's a simple array of constants mapped to these cards. Look for `contributors.jsx` in the code. It also has code comments for easier understanding 

Alternatively, to know how these cards work, you can look at the video attached in the main `Readme.md`

**Comment by Ayusht777** [comment]
and can you assigned it
