### ISSUE TITLE
Make an attractive contact us page 

### ISSUE THREAD

**Issue by its-harsshhh** [gdsc-abesit/GDSC-ABESIT#77]
This is the current UI of the contact us page.
<img width="1409" alt="Screenshot 2023-10-21 at 2 16 10 PM" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/91140636/fc69a431-e3fb-44fc-8a40-d63c3781c908">

**Comment by DebidYadav** [comment]
Hey, can you assign this issue to me and mark it in under hacktoberfest label?

**Comment by DebidYadav** [comment]
Please check PR. Thanks

**Comment by DebidYadav** [comment]
Please check PR.
