### ISSUE TITLE
add gdsc abesit logo in navigation bar

### ISSUE THREAD

**Issue by its-harsshhh** [gdsc-abesit/GDSC-ABESIT#78]
This is how it is looking now.
<img width="1304" alt="Screenshot 2023-10-21 at 2 17 23 PM" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/91140636/b691e2f2-6cc8-42a0-8a96-bc8ce2bc4fb5">

<br>
you can take gdsc abesit logo from here : https://drive.google.com/drive/folders/1Dz2H2DcGxHtlZX_hYFYHo3bzQPbhmP7E?usp=share_link

**Comment by sujithyadav998** [comment]
hello , assign this to me .

**Comment by Ishaan2053** [comment]
Sure go ahead!

**Comment by sujithyadav998** [comment]
<img width="949" alt="Screenshot 2023-10-21 222146" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/88442916/952bed78-fb4e-47ca-bbf3-831c86e45aca">
This is how website look after changing logo
