### ISSUE TITLE
Update website footer 

### ISSUE THREAD

**Issue by its-harsshhh** [gdsc-abesit/GDSC-ABESIT#79]
this is how its looking now
<img width="1440" alt="Screenshot 2023-10-21 at 2 24 30 PM" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/91140636/2ea47597-a1d3-4adf-b186-c9abe1630fd9">

**Comment by BreakTos** [comment]
Hello , can this take this one ?

**Comment by Ishaan2053** [comment]
Sure! go ahead start working. I'll assign you to it

**Comment by its-harsshhh** [comment]
@BreakTos are you working on this?

**Comment by BreakTos** [comment]
I wasn't really good at tailwind so it was taking time and i got caught with other things , Please assign it to someone else who might be interested . Sorry again
