### ISSUE TITLE
Navigation bar overlap Contributors Page

### ISSUE THREAD

**Issue by HarshitSharma4** [gdsc-abesit/GDSC-ABESIT#87]
Navigation bar is overlapping the content of Contributors Page

![Screenshot from 2023-10-22 22-21-19](https://github.com/gdsc-abesit/GDSC-ABESIT/assets/106171546/887b315a-c755-478c-b03e-f889d6507f9a)

**Comment by DebidYadav** [comment]
Can you assign it to me?

**Comment by DebidYadav** [comment]
> Can you assign it to me?

Opened the PR, please check.
