### ISSUE TITLE
Extracting The data from contributed file to a separate data file 

### ISSUE THREAD

**Issue by Ayusht777** [gdsc-abesit/GDSC-ABESIT#90]
hi i want to remove the data of contributors from  contribute components to a local data.js file where it will be essay to read the code and act as separate file

**Comment by Ayusht777** [comment]
also can all the contribute can be sorted  according to some category like UI/UX part ,coding ,etc would be great

**Comment by Ishaan2053** [comment]
Agreed, having the contributors' data in a separate file would be cleaner. Please make a new folder under which a file named `contributorData` should exist, holding the contributors' array. 

Sorting out contributors though is something we need finalize before we go ahead with it. For that, I request you to open a new issue detailing how you wish to realise this feature implementation.

For the moment, you'll be assigned this issue.

**Comment by Ayusht777** [comment]
ok i will separated the data
