### ISSUE TITLE
Contributors page UI fix on mobile screens

### ISSUE THREAD

**Issue by Suhaani07** [gdsc-abesit/GDSC-ABESIT#91]
On mobile screen the contributors page image is not rendering properly. 

<img width="361" alt="image" src="https://github.com/gdsc-abesit/GDSC-ABESIT/assets/98284331/afa801f1-baa3-4dff-83a0-1ea822801aed">

Kindly assign me this issue under Hacktoberfest 2023 to fix it.

**Comment by Ishaan2053** [comment]
Sure, you can start working on this. Please make sure though that the current appearance of images inside these cards on larger screen devices isn't affected. Also, it'd be great if you could detail the changes made within your PR.

I'll assign you to this issue.

**Comment by Suhaani07** [comment]
@Ishaan2053 have made the pull request. Kindly review it and let me know
